// Study abroad countries with their currencies
export const STUDY_ABROAD_COUNTRIES = [
    // 🌍 Africa
    { name: "Afghanistan", currency: "AFN" },
    { name: "Albania", currency: "ALL" },
    { name: "Algeria", currency: "DZD" },
    { name: "Angola", currency: "AOA" },
    { name: "Benin", currency: "XOF" },
    { name: "Botswana", currency: "BWP" },
    { name: "Burkina Faso", currency: "XOF" },
    { name: "Burundi", currency: "BIF" },
    { name: "Cameroon", currency: "XAF" },
    { name: "Cape Verde", currency: "CVE" },
    { name: "Central African Republic", currency: "XAF" },
    { name: "Chad", currency: "XAF" },
    { name: "Comoros", currency: "KMF" },
    { name: "Congo", currency: "XAF" },
    { name: "DR Congo", currency: "CDF" },
    { name: "Djibouti", currency: "DJF" },
    { name: "Egypt", currency: "EGP" },
    { name: "Equatorial Guinea", currency: "XAF" },
    { name: "Eritrea", currency: "ERN" },
    { name: "Ethiopia", currency: "ETB" },
    { name: "Gabon", currency: "XAF" },
    { name: "Gambia", currency: "GMD" },
    { name: "Ghana", currency: "GHS" },
    { name: "Guinea", currency: "GNF" },
    { name: "Kenya", currency: "KES" },
    { name: "Lesotho", currency: "LSL" },
    { name: "Liberia", currency: "LRD" },
    { name: "Libya", currency: "LYD" },
    { name: "Madagascar", currency: "MGA" },
    { name: "Malawi", currency: "MWK" },
    { name: "Mali", currency: "XOF" },
    { name: "Mauritania", currency: "MRU" },
    { name: "Mauritius", currency: "MUR" },
    { name: "Malta", currency: "EUR" },
    { name: "Morocco", currency: "MAD" },
    { name: "Mozambique", currency: "MZN" },
    { name: "Namibia", currency: "NAD" },
    { name: "Niger", currency: "XOF" },
    { name: "Nigeria", currency: "NGN" },
    { name: "Rwanda", currency: "RWF" },
    { name: "Senegal", currency: "XOF" },
    { name: "Sierra Leone", currency: "SLL" },
    { name: "Somalia", currency: "SOS" },
    { name: "South Africa", currency: "ZAR" },
    { name: "South Sudan", currency: "SSP" },
    { name: "Sudan", currency: "SDG" },
    { name: "Tanzania", currency: "TZS" },
    { name: "Togo", currency: "XOF" },
    { name: "Tunisia", currency: "TND" },
    { name: "Uganda", currency: "UGX" },
    { name: "Zambia", currency: "ZMW" },
    { name: "Zimbabwe", currency: "ZWL" },

    // 🌍 Europe
    { name: "Albania", currency: "ALL" },
    { name: "Austria", currency: "EUR" },
    { name: "Belgium", currency: "EUR" },
    { name: "Bosnia and Herzegovina", currency: "BAM" },
    { name: "Bulgaria", currency: "BGN" },
    { name: "Croatia", currency: "EUR" },
    { name: "Czech Republic", currency: "CZK" },
    { name: "Denmark", currency: "DKK" },
    { name: "Estonia", currency: "EUR" },
    { name: "Finland", currency: "EUR" },
    { name: "France", currency: "EUR" },
    { name: "Germany", currency: "EUR" },
    { name: "Greece", currency: "EUR" },
    { name: "Hungary", currency: "HUF" },
    { name: "Iceland", currency: "ISK" },
    { name: "Ireland", currency: "EUR" },
    { name: "Italy", currency: "EUR" },
    { name: "Latvia", currency: "EUR" },
    { name: "Lithuania", currency: "EUR" },
    { name: "Luxembourg", currency: "EUR" },
    { name: "Netherlands", currency: "EUR" },
    { name: "Norway", currency: "NOK" },
    { name: "Poland", currency: "PLN" },
    { name: "Portugal", currency: "EUR" },
    { name: "Romania", currency: "RON" },
    { name: "Slovakia", currency: "EUR" },
    { name: "Slovenia", currency: "EUR" },
    { name: "Spain", currency: "EUR" },
    { name: "Sweden", currency: "SEK" },
    { name: "Switzerland", currency: "CHF" },
    { name: "United Kingdom", currency: "GBP" },

    // 🌏 Asia
    { name: "India", currency: "INR" },
    { name: "China", currency: "CNY" },
    { name: "Japan", currency: "JPY" },
    { name: "South Korea", currency: "KRW" },
    { name: "Pakistan", currency: "PKR" },
    { name: "Bangladesh", currency: "BDT" },
    { name: "Sri Lanka", currency: "LKR" },
    { name: "Nepal", currency: "NPR" },
    { name: "Bhutan", currency: "BTN" },
    { name: "Myanmar", currency: "MMK" },
    { name: "Thailand", currency: "THB" },
    { name: "Vietnam", currency: "VND" },
    { name: "Malaysia", currency: "MYR" },
    { name: "Singapore", currency: "SGD" },
    { name: "Indonesia", currency: "IDR" },
    { name: "Philippines", currency: "PHP" },
    { name: "Cambodia", currency: "KHR" },
    { name: "Laos", currency: "LAK" },
    { name: "Mongolia", currency: "MNT" },
    { name: "Saudi Arabia", currency: "SAR" },
    { name: "United Arab Emirates", currency: "AED" },
    { name: "Qatar", currency: "QAR" },
    { name: "Kuwait", currency: "KWD" },
    { name: "Oman", currency: "OMR" },
    { name: "Israel", currency: "ILS" },
    { name: "Turkey", currency: "TRY" },

    // 🌎 Americas
    { name: "United States", currency: "USD" },
    { name: "Canada", currency: "CAD" },
    { name: "Mexico", currency: "MXN" },
    { name: "Brazil", currency: "BRL" },
    { name: "Argentina", currency: "ARS" },
    { name: "Chile", currency: "CLP" },
    { name: "Colombia", currency: "COP" },
    { name: "Peru", currency: "PEN" },
    { name: "Venezuela", currency: "VES" },

    // 🌏 Oceania
    { name: "Australia", currency: "AUD" },
    { name: "New Zealand", currency: "NZD" },
    { name: "Fiji", currency: "FJD" },
    { name: "Papua New Guinea", currency: "PGK" }
];

// All available currencies (ISO 4217)
export const CURRENCIES = [
    // Major
    "USD", "EUR", "GBP", "JPY", "CNY", "CHF", "CAD", "AUD", "NZD",

    // Asia
    "INR", "PKR", "BDT", "LKR", "NPR", "BTN",
    "MMK", "THB", "VND", "MYR", "SGD", "IDR",
    "PHP", "KHR", "LAK", "MNT", "KRW", "HKD",
    "TWD", "JPY",

    // Middle East
    "AED", "SAR", "QAR", "KWD", "OMR", "BHD",
    "ILS", "TRY", "IRR", "IQD", "JOD", "LBP",
    "YER",

    // Europe (non-EUR)
    "SEK", "NOK", "DKK", "ISK", "PLN", "CZK",
    "HUF", "RON", "BGN", "ALL", "BAM", "MKD",
    "RSD", "UAH", "BYN", "MDL", "GEL", "AMD",
    "AZN", "RUB",

    // Africa
    "ZAR", "NGN", "EGP", "KES", "UGX", "TZS",
    "GHS", "ETB", "MAD", "DZD", "TND", "LYD",
    "SDG", "SSP", "ZMW", "ZWL", "MWK", "MUR",
    "NAD", "BWP", "XOF", "XAF", "CDF", "RWF",
    "BIF", "SLL", "SOS", "DJF", "KMF", "CVE",

    // Americas
    "MXN", "BRL", "ARS", "CLP", "COP", "PEN",
    "UYU", "PYG", "BOB", "VES", "CRC", "GTQ",
    "HNL", "NIO", "PAB", "DOP", "HTG", "JMD",
    "TTD", "BBD", "BSD", "XCD", "GYD", "SRD",

    // Oceania
    "FJD", "PGK", "SBD", "VUV", "WST", "TOP",

    // Special / shared
    "XPF", "XAF", "XOF", "XCD"
];